spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    flyway:
      locations: classpath:db/migration
      baseline-on-migrate: true

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /documentation.html