CREATE TABLE tab_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   total_price DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_tab_order PRIMARY KEY (id)
);

CREATE TABLE tab_order_pizzas (
  order_id BIGINT NOT NULL,
   pizza_id BIGINT NOT NULL
);

ALTER TABLE tab_order_pizzas ADD CONSTRAINT fk_tabordpiz_on_order FOREIGN KEY (order_id) REFERENCES tab_order (id);

ALTER TABLE tab_order_pizzas ADD CONSTRAINT fk_tabordpiz_on_pizza FOREIGN KEY (pizza_id) REFERENCES pizza (id);